kind: Deployment
apiVersion: apps/v1
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: bibinlincy/healthcareproject:1
          ports:
            - containerPort: 8082
---

kind: Service
apiVersion: v1
metadata:
  name: healthcare
spec:
  ports:
    - port: 80 
      targetPort: 8082
      nodePort: 30007
  selector:
    app: healthcare
  type: NodePort
